wandb_version: 1

dataset:
  desc: null
  value: SST2
batch_size:
  desc: null
  value: 8
set_pad_id:
  desc: null
  value: true
max_length:
  desc: null
  value: 512
_wandb:
  desc: null
  value:
    python_version: 3.10.18
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.57.1
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1762008329.0
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 84
      - 98
      - 100
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 84
      - 98
      - 100
      3:
      - 13
      - 16
      - 23
      4: 3.10.18
      5: 0.16.6
      6: 4.57.1
      8:
      - 2
      - 5
      13: linux-x86_64
